- name : catalogue
  hosts : catalogue
  become : yes
  tasks:
    - name : disabling the previous nodejs package 
      ansible.builtin.command :
        cmd: "dnf module disable nodejs -y"

    - name : enabling the new nodejs package 
      ansible.builtin.command :
        cmd: "dnf module enable nodejs:18 -y"

        # or below cmd we can use instead above two for disable and enable
    # - name : enabling and disabling node js 
    #   ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y 


    - name : Install node js package
      ansible.builtin.package:
        name : nodejs
        state : present

    - name : creating user roboshop
      ansible.builtin.user:
          name : roboshop
    
    - name : creating app directory
      ansible.builtin.file:
        path : /app
        state: directory

    - name : downloading the application code of catalogue
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name : unzipping the catalogue.js file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name : installing npm dependecies
      ansible.builtin.command:  npm install
      args :
        chdir : /app

    - name: setting up systemd that is catalogue service
      ansible.builtin.copy:
        src : catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name : deamon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name :  setup MongoDB repo 
      ansible.builtin.copy:
        src : mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name : install mongodb-client
      ansible.builtin.package:
        name : mongodb-org-shell
        state: present

    - name : get the categories/products count present in catalogue.service file
      ansible.builtin.command:
        register : product_count    #storing the list of or output of catalogue.service file products in product_count variable

    - name : print the list of products stored in product_count variable
      ansible.builtin.command:
        echo : "products lsit is : {{product_count}}"

    - name : loading the data to the catalogue
      ansible.builtin.command : mongo --host mongodb-arundev.online < /app/schema/catalogue.service
      when : product_count. stdout == 0      #basically in terminal stdout shows the no of products present

      

