- name : redis
  hosts: redis
  become : yes
  tasks:
    # - name : installing remi release
    #   ansible.builtin.command:
    #     cmd: "dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y"

    - name : install remi release
      ansible.builtin.dnf:
        name : https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state : present
        disable_gpg_check: true


    - name : enabling the redis:remi-6.2 package 
      ansible.builtin.command :
        cmd: "dnf module enable redis:remi-6.2 -y"

    - name: Install redis package
      ansible.builtin.package:
        name: redis
        state: present

    - name: Replace old hostname with new hostname allow remote connections
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name : enable and start the redis
      ansible.builtin.service:
        name : redis
        state : restarted
        enabled : true
