- name : redis
  hosts: redis
  tasks:
    - name : installing redis repo file as a rpm
      ansible.builtin.get_url:
        cmd: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"


    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: redis:remi-6.2
        enabled: yes

    - name: Install ntpdate
      ansible.builtin.package:
        name: redis
        state: present
