- name : redis
  hosts: redis
  tasks:
    - name : installing redis repo file as a rpm
      ansible.builtin.command:
        cmd: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y"


    - name : enabling the redis:remi-6.2 package 
      ansible.builtin.command :
        cmd: "dnf module enable redis:remi-6.2 -y"

    - name: Install ntpdate
      ansible.builtin.package:
        name: redis
        state: present
